### ISSUE TITLE
Rebase mainline branch to make `.git` directory smaller

### ISSUE THREAD

**Issue by nateinaction** [proveskit/fprime-proves#9]
Hey team,

Due to the previous inclusion of the python venv files removed in #2, we have a `.git` directory that's 175MB large. This is probably fine for most folks with a high speed connection but we could improve developer experience during the cloning/forking process by rewriting the history for the repo's first commit.

Rewriting history in git can be a big deal if we have many changes and contributors. However, if we believe this repository will be here for the long term, it feels like a good thing to do now while its contributor list is small.

From this repo:
```sh
du -h -d 1 ./.git/objects/pack
175M	./.git/objects/pack
```

Example of another fprime repo:
```
du -h -d 1 ./.git/objects/pack
  0B	./.git/objects/pack
```

Thoughts?

**Comment by Mikefly123** [comment]
This change looks good to me! I went ahead and made you a repo admin so you can do what needs to be done.

**Comment by nateinaction** [comment]
Done! 🙃 
```sh
git-filter-repo --path fprime-venv-back --invert-paths
...
du -h -d 1 ./.git/objects/pack
612K	./.git/objects/pack
```
